default: &default
  adapter: postgresql
  encoding: unicode
  # For details on connection pooling, see Rails configuration guide
  # https://guides.rubyonrails.org/configuring.html#database-pooling
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  extension: pgcrypto

development:
  <<: *default
  database: wallet_api_development

test:
  <<: *default
  database: wallet_api_test

production:
  <<: *default
  database: wallet_api_production
  username: wallet_api
  password: <%= ENV["WALLET_API_DATABASE_PASSWORD"] %>
